### ISSUE TITLE
Site Not Found - request new cloud place

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/adventistplace-issues#112] opened 2017-10-10 05:19 UTC
New Site not found - if searching for a place and it's not there, a "Can't find place" link (maybe at the bottom of the the search dropdown results) opens a pop up: "if you've searched for an existing church or entity which could not be found, send a request to have the place created here", and link to a form with similar fields to the old SC form, or have the essential details listed in the first popup and a submit button. 
It goes to the 'Conference', based on the one they selected, and conference should get notification of the submission and have a quick 'click through' process to approve/edit the submission in their master area.
THEN that admin should later receive notification (and even admin access automatically?) when that request is actioned.

**Comment by danlewis** [comment] 2017-10-10 23:11
This really needs the Adventist Cloud to function.. I don't think the Adventist Cloud will be happening this year but we still need to go ahead. Maybe we'll create a little temporary Adventist cloud..

**Comment by Scotttie** [comment] 2017-10-17 06:30
keeping open until the Cloud forms.

**Comment by danlewis** [comment] 2018-03-22 06:31
duplicate of #185

**Closed by danlewis** 2018-03-22 06:31 UTC
Labels: V2, enhancement, feature incomplete
